spring:
  datasource:
    username: root
    password: rnTlb2#t
    url: jdbc:mysql://movieapi.cjwgyc0ayecm.eu-north-1.rds.amazonaws.com:3306/movies_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: posters/

base:
  url: "http://localhost:8090"

server:
  port: 8090